### ISSUE TITLE
Issue with battle outcome

### ISSUE THREAD

**Issue by Cultistoverlord** [joshdeboer/itc-battles-app#42]
When I do the scoring for a battle and go to homepage, it says that both sides won the battle. (Even if it's a really ckear outcome) I have checked online and I'm not doing anything wrong in the app. Thank you anyway, your app is great: it's just one small issue!

**Comment by joshdeboer** [comment]
Thanks for submitting the issue! I think this is just a problem with how the data is presented. All of the stats on the homepage are _your_ stats; there are no stats for your opponents. It shows a win under your faction and your opponent's faction because you won with your faction, and you won against your opponent's faction. I'm going to change the wording slightly to hopefully make things clearer.
